[2024-06-23T23:46:42.988+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T23:46:43.011+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_to_s3.transform_nasa_data manual__2024-06-23T23:41:34.508993+00:00 [queued]>
[2024-06-23T23:46:43.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_to_s3.transform_nasa_data manual__2024-06-23T23:41:34.508993+00:00 [queued]>
[2024-06-23T23:46:43.017+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-23T23:46:43.028+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_nasa_data> on 2024-06-23 23:41:34.508993+00:00
[2024-06-23T23:46:43.035+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1419) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T23:46:43.038+0000] {standard_task_runner.py:63} INFO - Started process 1421 to run task
[2024-06-23T23:46:43.036+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nasa_to_s3', 'transform_nasa_data', 'manual__2024-06-23T23:41:34.508993+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/extractAPIdata.py', '--cfg-path', '/tmp/tmprpww_wg5']
[2024-06-23T23:46:43.039+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask transform_nasa_data
[2024-06-23T23:46:43.086+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_to_s3.transform_nasa_data manual__2024-06-23T23:41:34.508993+00:00 [running]> on host e0fa33b4439a
[2024-06-23T23:46:43.170+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test' AIRFLOW_CTX_DAG_ID='nasa_to_s3' AIRFLOW_CTX_TASK_ID='transform_nasa_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T23:41:34.508993+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T23:41:34.508993+00:00'
[2024-06-23T23:46:43.171+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T23:46:43.193+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T23:46:43.193+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extractAPIdata.py", line 19, in transform_data
    df = pd.DataFrame(response["name"])
                      ~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-06-23T23:46:43.205+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nasa_to_s3, task_id=transform_nasa_data, run_id=manual__2024-06-23T23:41:34.508993+00:00, execution_date=20240623T234134, start_date=20240623T234643, end_date=20240623T234643
[2024-06-23T23:46:43.221+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task transform_nasa_data ('NoneType' object is not subscriptable; 1421)
[2024-06-23T23:46:43.254+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T23:46:43.276+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T23:46:43.277+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
